# Generated by Django 5.0.6 on 2024-07-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
